TehnokratProject/Areas/Admin/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TehnokratProject.Data;
using TehnokratProject.Models;

namespace TehnokratProject.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class CategoryController : Controller
    {
        ApplicationDbContext db;
        public CategoryController(ApplicationDbContext context)
        {
            db = context;
        }

        public async Task<IActionResult> Index()
        {
            List<Category> categories = await db.categories.ToListAsync();
            return View(categories);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Category category)
        {
            db.categories.Add(category);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> EditPost(Category category)
        {
            db.categories.Update(category);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id != null)
            {
                Category? category = await db.categories.FirstOrDefaultAsync(c => c.id == id);
                if (category != null)
                {
                    return View(category);
                }
            }
            return NotFound();
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id != null)
            {
                Category? category = await db.categories.FirstOrDefaultAsync(p => p.id == id);
                if (category != null)
                {
                    db.categories.Remove(category);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
            }
            return NotFound();
        }
    }
}

TehnokratProject/Areas/User/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using TehnokratProject.Areas.User.ViewModels;
using TehnokratProject.Data;
using TehnokratProject.Models;

namespace TehnokratProject.Areas.User.Controllers
{
    [Area("User")]
    public class ProductController : Controller
    {
        ApplicationDbContext db;

        public ProductController(ApplicationDbContext context)
        {
            db = context;
        }

        [HttpGet]
        public IActionResult Index(ProductFilterModel filter, int page = 1, int pageSize = 12)
        {
            var query = db.products.Include(p => p.Images).AsQueryable();

            // Мінімальна ціна
            if (filter.MinPrice.HasValue)
                query = query.Where(p => p.price >= filter.MinPrice.Value);

            // Максимальна ціна
            if (filter.MaxPrice.HasValue)
                query = query.Where(p => p.price <= filter.MaxPrice.Value);

            // Категорії
            if (filter.Categories != null && filter.Categories.Any())
                query = query.Where(p => filter.Categories.Contains(p.category.title));

            // Бренди
            if (filter.Brands != null && filter.Brands.Any())
                query = query.Where(p => filter.Brands.Contains(p.brand));

            // СТАН: "Новий", "Б/у" тощо
            if (filter.States != null && filter.States.Any())
                query = query.Where(p => filter.States.Contains(p.state));

            if (filter.Quantity != null && filter.Quantity.Any())
            {
                query = query.Where(p =>
                    (filter.Quantity.Contains("в наявності") && p.quantity > 0) ||
                    (filter.Quantity.Contains("немає в наявності") && p.quantity <= 0)
                );
            }


            // Підрахунок сторінок
            int totalItems = query.Count();
            int totalPages = (int)Math.Ceiling((double)totalItems / pageSize);

            var products = query
                .Skip((page - 1) * pageSize)
                .Take(pageSize)
                .ToList();

            var model = new ProductFilterPageViewModel
            {
                Categories = db.categories.ToList(),
                Brands = new List<string>{"Без бренду",
                // Смартфони / Гаджети
                "Apple", "Samsung", "Xiaomi", "Huawei", "OnePlus", "Oppo", "Realme", "Sony", "Google", "Nokia",
                // Ноутбуки / Комп’ютери
                "ASUS", "Acer", "Dell", "HP", "Lenovo", "MSI", "Razer",
                // Телевізори / Smart TV
                "TCL", "Hisense", "Panasonic", "Philips", "Sharp",
                // Аудіо / Навушники / Колонки
                "JBL", "Bose", "Beats",
                // Ігрова техніка
                "Nintendo", "Logitech", "HyperX", "Corsair",
                // Принтери / Периферія
                "Epson", "Trust", "Xerox",  },   
                Filters = filter,
                Products = products,
                CurrentPage = page,
                TotalPages = totalPages,
                PageSize = pageSize
            };

            return View(model);
        }


        public IActionResult Home()
        {
            return View();
        }
    }
}

TehnokratProject/Controllers/FeedbackController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TehnokratProject.Data;
using TehnokratProject.Models;

namespace TehnokratProject.Controllers
{
    public class FeedbackController : Controller
    {
        ApplicationDbContext db;
        public FeedbackController(ApplicationDbContext context)
        {
            db = context;
        }
        public async Task<IActionResult> Index()
        {
            List<Feedback> feedbacks = await db.feedbacks.ToListAsync();
            return View(feedbacks);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Feedback feedback)
        {
            feedback.date = DateTime.Now;
            db.feedbacks.Add(feedback);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> EditPost(Feedback feedbacks)
        {
            db.feedbacks.Update(feedbacks);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id != null)
            {
                Feedback? feedback = await db.feedbacks.FirstOrDefaultAsync(c => c.id == id);
                if (feedback != null)
                {
                    return View(feedback);
                }
            }
            return NotFound();
        }



        

      

        public IActionResult Delete()
        {
            return View();
        }
    }
}

TehnokratProject/Areas/Admin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TehnokratProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/admin_styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TehnokratProject.styles.css" asp-append-version="true" />
</head>
<body>
     <h3>Сторінка адміністратора</h3>
    <a class="nav-link text-dark" asp-area="User"  asp-controller="Product" asp-action="Index">Користувач</a>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>

                </button>


                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                        <img class="main_logo_img" src="~/img/logo/logo_technokrat.jpg" />
                    </a>
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Category" asp-action="Index">Категорії</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Product" asp-action="Index">Товари</a>
                        </li>
                        @* <li class="nav-item"> *@
                        @*     <a class="nav-link text-dark" asp-controller="Problem" asp-action="Index">Несправдності</a> *@
                        @* </li> *@
                        @* <li class="nav-item"> *@
                        @*     <a class="nav-link text-dark" asp-controller="Solution" asp-action="Index">Рішення несправностей</a> *@
                        @* </li> 
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Feedback" asp-action="Index">Відгуки</a>
                        </li>   
                         *@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TehnokratProject/Areas/Admin/Views/Shared/_AdminLoginLayout.cshtml
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<link rel="stylesheet" href="~/css/admin_styles.css" asp-append-version="true" />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
@RenderBody()