TehnokratProject/Areas/User/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using TehnokratProject.Areas.User.ViewModels;
using TehnokratProject.Data;
using TehnokratProject.Models;

namespace TehnokratProject.Areas.User.Controllers
{
    [Area("User")]
    public class ProductController : Controller
    {
        ApplicationDbContext db;

        public ProductController(ApplicationDbContext context)
        {
            db = context;
        }

        [HttpGet]
        public IActionResult Index(ProductFilterModel filter, int page = 1, int pageSize = 12)
        {
            var query = db.products.Include(p => p.Images).AsQueryable();

            // Мінімальна ціна
            if (filter.MinPrice.HasValue)
                query = query.Where(p => p.price >= filter.MinPrice.Value);

            // Максимальна ціна
            if (filter.MaxPrice.HasValue)
                query = query.Where(p => p.price <= filter.MaxPrice.Value);

            // Категорії
            if (filter.Categories != null && filter.Categories.Any())
                query = query.Where(p => filter.Categories.Contains(p.category.title));

            // Бренди
            if (filter.Brands != null && filter.Brands.Any())
                query = query.Where(p => filter.Brands.Contains(p.brand));

            // СТАН: "Новий", "Б/у" тощо
            if (filter.States != null && filter.States.Any())
                query = query.Where(p => filter.States.Contains(p.state));

            if (filter.Quantity != null && filter.Quantity.Any())
            {
                query = query.Where(p =>
                    (filter.Quantity.Contains("в наявності") && p.quantity > 0) ||
                    (filter.Quantity.Contains("немає в наявності") && p.quantity <= 0)
                );
            }


            // Підрахунок сторінок
            int totalItems = query.Count();
            int totalPages = (int)Math.Ceiling((double)totalItems / pageSize);

            var products = query
                .Skip((page - 1) * pageSize)
                .Take(pageSize)
                .ToList();

            var model = new ProductFilterPageViewModel
            {
                Categories = db.categories.ToList(),
                Brands = new List<string>{"Без бренду",
                // Смартфони / Гаджети
                "Apple", "Samsung", "Xiaomi", "Huawei", "OnePlus", "Oppo", "Realme", "Sony", "Google", "Nokia",
                // Ноутбуки / Комп’ютери
                "ASUS", "Acer", "Dell", "HP", "Lenovo", "MSI", "Razer",
                // Телевізори / Smart TV
                "TCL", "Hisense", "Panasonic", "Philips", "Sharp",
                // Аудіо / Навушники / Колонки
                "JBL", "Bose", "Beats",
                // Ігрова техніка
                "Nintendo", "Logitech", "HyperX", "Corsair",
                // Принтери / Периферія
                "Epson", "Trust", "Xerox",  },   
                Filters = filter,
                Products = products,
                CurrentPage = page,
                TotalPages = totalPages,
                PageSize = pageSize
            };

            return View(model);
        }


        public IActionResult Home()
        {
            return View();
        }
    }
}

TehnokratProject/Areas/User/Controllers/ServicesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TehnokratProject.Data;
using TehnokratProject.Models;

namespace TehnokratProject.Areas.User.Controllers
{
    [Area("User")]
    public class ServicesController:Controller
    {

        public IActionResult List()
        {
            return View();
        }

        public IActionResult Phone()
        {
            return View();
        }

        public IActionResult Laptop()
        {
            return View();
        }

        public IActionResult Printer()
        {
            return View();
        }

        public IActionResult TV()
        {
            return View();
        }

        public IActionResult PC()
        {
            return View();
        }

        public IActionResult Tablet()
        {
            return View();
        }

    }
}

TehnokratProject/Areas/User/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="uk">
<head>
    <meta charset="utf-8" />
    <title>@ViewData["Title"] - Technokrat</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link href="https://cdn.jsdelivr.net/combine/npm/daisyui@5/base/reset.css,npm/daisyui@5/base/svg.css,npm/daisyui@5/base/properties.css,npm/daisyui@5/base/rootscrollgutter.css,npm/daisyui@5/base/scrollbar.css,npm/daisyui@5/base/rootscrolllock.css,npm/daisyui@5/components/button.css,npm/daisyui@5/components/modal.css,npm/daisyui@5/theme/light.css"
          rel="stylesheet"
          type="text/css" />

    <!-- Локальні стилі -->
    @* <link rel="stylesheet" href="~/css/global.css" asp-append-version="true" /> *@
    <link rel="stylesheet" href="~/css/@ViewData["PageCss"]" asp-append-version="true" />

    <link rel="icon" href="~/assets/imgs/favicon.ico" type="image/x-icon" />
</head>
<body>
    <div id="image-preview" style="display: none; position: absolute; z-index: 9999; pointer-events: none;">
        <img id="image-preview-img" src="" style="max-width: 300px; max-height: 300px; border-radius: 8px; box-shadow: 0 4px 10px rgba(0,0,0,0.3);" />
    </div>
    <!-- Mobile Header -->
    <header class="new_header mobile-only">
        <div class="new_header__second_row">
            <a href="/">
                <img src="/assets/imgs/logo.svg" alt="Logo" />
            </a>
            <div class="new_header__second_row__mobile_group">
                <label for="order-consultation-modal" class="phone-icon-mobile">
                    <svg width="44"
                         height="44"
                         viewBox="0 0 44 44"
                         fill="none"
                         xmlns="http://www.w3.org/2000/svg">
                        <path d="M18 13C18.5 13 20.5 17.5 20.5 18C20.5 19 19 20 18.5 21C18 22 19 23 20 24C20.39 24.39 22 26 23 25.5C24 25 25 23.5 26 23.5C26.5 23.5 31 25.5 31 26C31 28 29.5 29.5 28 30C26.5 30.5 25.5 30.5 23.5 30C21.5 29.5 20 29 17.5 26.5C15 24 14.5 22.5 14 20.5C13.5 18.5 13.5 17.5 14 16C14.5 14.5 16 13 18 13Z"
                              stroke="black"
                              stroke-width="2"
                              stroke-linecap="round"
                              stroke-linejoin="round" />
                    </svg>
                </label>
                <div class="new_header__second_row__mobile_group__menu_button">
                    <svg width="24"
                         height="24"
                         viewBox="0 0 24 24"
                         fill="none"
                         xmlns="http://www.w3.org/2000/svg">
                        <path d="M4.125 7.125H19.875M4.125 12H19.875M4.125 16.875H19.875"
                              stroke="black"
                              stroke-width="1.5"
                              stroke-miterlimit="10"
                              stroke-linecap="round" />
                    </svg>
                </div>
            </div>
        </div>
    </header>

    <!-- Desktop Header -->
    <header class="desktop-header desktop-only">
        <div class="container">
            <div class="desktop-header__top">
                <div class="desktop-header__contact-info">
                    <div class="desktop-header__phone-numbers">
                        <img src="/assets/imgs/phone.svg" alt="Phone" loading="lazy" />
                        <a>067-872-44-64 (Viber)</a>
                        <a>066-200-77-84</a>
                    </div>
                    <div class="desktop-header__location">
                        <img src="/assets/imgs/geo.svg" alt="Location" loading="lazy" />
                        <span>м. Бровари, вул. Незалежності, 2, СЦ «Технократ»</span>
                    </div>
                </div>
            </div>

            <div class="desktop-header__main">
                <a href="/" class="desktop-header__logo">
                    <img src="/assets/imgs/logo.svg" alt="Технократ" />
                </a>

                <nav class="desktop-header__nav">
                    <ul class="desktop-header__nav-list">
                        <li>
                            <a asp-area="User" asp-controller="Services" asp-action="List">Послуги</a>
                        </li>
                        <li>
                            <a asp-area="User" asp-controller="Product" asp-action="Index">Товари</a>
                        </li>
                        <li>
                            <a asp-area="User" asp-controller="Home" asp-action="About">Про нас</a>
                        </li>
                        <li>
                            <a asp-area="User" asp-controller="Home" asp-action="Contacts">Контакти</a>
                        </li>
                    </ul>
                </nav>

                <a asp-area="User" asp-controller="Application" asp-action="Help" for="order-product-modal" class="desktop-header__order-btn">Замовити ремонт</a>
            </div>
        </div>
    </header>

    <div class="mobile-menu-overlay" id="mobileMenu" style="display: none">
        <div class="mobile-menu__header">
            <img src="/assets/imgs/logo.svg" alt="Logo" class="mobile-menu__logo" />
            <button class="mobile-menu__close"
                    id="closeMobileMenu"
                    aria-label="Закрити меню">
                <svg width="24"
                     height="24"
                     viewBox="0 0 24 24"
                     fill="none"
                     xmlns="http://www.w3.org/2000/svg">
                    <path d="M11.9998 13.3998L7.0998 18.2998C6.91647 18.4831 6.68314 18.5748 6.3998 18.5748C6.11647 18.5748 5.88314 18.4831 5.6998 18.2998C5.51647 18.1165 5.4248 17.8831 5.4248 17.5998C5.4248 17.3165 5.51647 17.0831 5.6998 16.8998L10.5998 11.9998L5.6998 7.0998C5.51647 6.91647 5.4248 6.68314 5.4248 6.3998C5.4248 6.11647 5.51647 5.88314 5.6998 5.6998C5.88314 5.51647 6.11647 5.4248 6.3998 5.4248C6.68314 5.4248 6.91647 5.51647 7.0998 5.6998L11.9998 10.5998L16.8998 5.6998C17.0831 5.51647 17.3165 5.4248 17.5998 5.4248C17.8831 5.4248 18.1165 5.51647 18.2998 5.6998C18.4831 5.88314 18.5748 6.11647 18.5748 6.3998C18.5748 6.68314 18.4831 6.91647 18.2998 7.0998L13.3998 11.9998L18.2998 16.8998C18.4831 17.0831 18.5748 17.3165 18.5748 17.5998C18.5748 17.8831 18.4831 18.1165 18.2998 18.2998C18.1165 18.4831 17.8831 18.5748 17.5998 18.5748C17.3165 18.5748 17.0831 18.4831 16.8998 18.2998L11.9998 13.3998Z"
                          fill="black" />
                </svg>
            </button>
        </div>
        <nav class="mobile-menu__nav">
            <ul>
                <li>
                    <a asp-area="User" asp-controller="Services" asp-action="List">Послуги</a>
                </li>
                <li>
                    <a asp-area="User" asp-controller="Product" asp-action="Index">Товари</a>
                </li>
                <li>
                    <a asp-area="User" asp-controller="Home" asp-action="About">Про нас</a>
                </li>
                <li>
                    <a asp-area="User" asp-controller="Home" asp-action="Contacts">Контакти</a>
                </li>
            </ul>
            <a asp-area="User" asp-controller="Application" asp-action="Help" for="order-product-modal" class="mobile-menu__order-btn">Замовити ремонт</a>
        </nav>
        <div class="mobile-menu__footer">
            <div class="mobile-menu__phones">
                <img src="/assets/imgs/phone.svg" alt="Phone" />
                <span>067-872-44-64 (Viber),</span>
                <span>066-200-77-84</span>
            </div>
            <div class="mobile-menu__location">
                <span>м. Бровари, вул. Незалежності, 2, СЦ «Технократ»</span>
            </div>
        </div>
    </div>


    @RenderBody()


    <footer class="footer">
        <div class="footer__container">
            <div class="footer__logos">
                <img src="/assets/imgs/sunrise_logo.webp"
                     alt="Sunrise Logo"
                     class="footer__sunrise-logo"
                     loading="lazy" />
                <img src="/assets/imgs/logo.svg"
                     alt="Logo"
                     class="footer__main-logo"
                     loading="lazy" />
            </div>
            <div class="footer__section">
                <div class="footer__section-title">Інформація</div>
                <div class="footer__section-link">
                    <a asp-area="User" asp-controller="Home" asp-action="About">Про нас</a>
                </div>
                <div class="footer__section-link">
                    <a asp-area="User" asp-controller="Services" asp-action="List">Ціни на послуги</a>
                </div>
                <div class="footer__section-link">
                    <a asp-area="User" asp-controller="Application" asp-action="Help" for="order-consultation-modal">Консультація</a>
                </div>
            </div>
            <div class="footer__section">
                <div class="footer__section-title">Послуги</div>
                <div class="footer__section-link">
                    <a asp-area="User" asp-controller="Services" asp-action="Phone">Ремонт телефонів</a>
                </div>
                <div class="footer__section-link"><a asp-area="User" asp-controller="Services" asp-action="Laptop">Ноутбуки</a></div>
                <div class="footer__section-link"><a asp-area="User" asp-controller="Services" asp-action="List">Інше</a></div>
            </div>
            <div class="footer__section">
                <div class="footer__section-title">Контакти</div>
                <div class="footer__contact-row">
                    <span>
                        <b>м. Бровари,</b><br />вул. Незалежності, 2, СЦ
                        «Технократ»
                    </span>
                </div>
                <div class="footer__contact-row">
                    <img src="/assets/imgs/clock.svg" alt="Clock" loading="lazy" />
                    <span>ПН-ПТ: 10:00–18:00</span>
                </div>
                <div class="footer__contact-row">
                    <img src="/assets/imgs/phone.svg" alt="Phone" loading="lazy" />
                    <span>067-872-44-64 (Viber)<br />066-200-77-84</span>
                </div>
            </div>
            <div class="footer__privacy">
                <div class="footer__copyright">
                    Copyright © 2025 Технократ. Усі права захищені
                </div>
                <div class="footer__privacy-links">
                    <a asp-area ="Admin" asp-controller="Account" asp-action="Login">Адміністратору</a>
                </div>
            </div>
        </div>
    </footer>
    @RenderSection("Scripts", required: false)
  
    
    <script src="~/js/main.js"></script>
    <script src="~/js/filters.js"></script>
</body>

</html>